### ISSUE TITLE
a txt

### ISSUE THREAD

**Issue by Sijko** [rainbowdesign/OxygenNotIncluded-Mods#1]
so why exactly does the "**AutoSweeperMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nulldebug.txt**" file is being created in the game dir? :)

**Comment by rainbowdesign** [comment]
pretty sure its a debug log that is in the wrong folder. When the buildingmanipulator was released and the sweeper mod is not obsolete I will fix it.
