### ISSUE TITLE
please make standalone mods

### ISSUE THREAD

**Issue by TyoAtrosa** [rainbowdesign/OxygenNotIncluded-Mods#4]
could you please split up some of your "modpacks" into smaller pieces? mainly building extensions, i really only need the background ladders.

**Comment by rainbowdesign** [comment]
I dont want to maintain every mod singly, i decided a while ago now to only make exciting world mod (well the autosweeper mod which i said i maintain but rather pass that too to someone else). The building extension adds other buildings at the end of each building page. It does nothing else and i really think you should try some namely the automopper and the laser miner, If you really *WANT* to have a mod with only the background ladder you can ask me for the code, but i will not maintain it.
