### ISSUE TITLE
Unable to build the automatic liquidforge

### ISSUE THREAD

**Issue by n8crafter** [rainbowdesign/OxygenNotIncluded-Mods#5]
the Automatic Liquidforge is unbuildable due to one of the material categories being broken. the material type is listed as MISSING.STRINGS.MISC.TAGS.GLAS
Looking at the recipes for the other automatic refineries, i get the feeling the material is intended to be Thermium.

**Comment by rainbowdesign** [comment]
It was supposed to be glas to have the new recipes early.
I will change it now it will be Thermium and i will add the recipes to the glasforge too. The fix will be in the next update.

**Comment by rainbowdesign** [comment]
Should be fixed
